"""Add status to room_task

Revision ID: 19e6825b4769
Revises: 8a17bdc117fc
Create Date: 2026-06-27 16:33:45.506752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e6825b4769'
down_revision: Union[str, Sequence[str], None] = '8a17bdc117fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_tasks', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_column('room_tasks', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('room_tasks', 'status')
    # ### end Alembic commands ###
