"""add memory reinforcement fields

Revision ID: 3f3313d8f246
Revises: baee00b484bb
Create Date: 2026-05-24 21:52:16.770216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3313d8f246'
down_revision: Union[str, Sequence[str], None] = 'baee00b484bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_memories')
    op.drop_table('room_join_requests')
    op.drop_table('collaborator_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('collaborator_requests_receiver_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('collaborator_requests_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collaborator_requests_pkey'))
    )
    op.create_table('room_join_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_join_requests_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('room_join_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_join_requests_pkey'))
    )
    op.create_table('room_memories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('memory_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('importance_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('access_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('room_memories_created_by_fkey')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_memories_room_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_memories_pkey'))
    )
    # ### end Alembic commands ###
