"""add room memories

Revision ID: 6abb7cc3eaa4
Revises: ef53d95d310e
Create Date: 2026-05-23 22:11:50.957461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6abb7cc3eaa4'
down_revision: Union[str, Sequence[str], None] = 'ef53d95d310e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_join_requests')
    op.drop_table('collaborator_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('collaborator_requests_receiver_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('collaborator_requests_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collaborator_requests_pkey'))
    )
    op.create_table('room_join_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_join_requests_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('room_join_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_join_requests_pkey'))
    )
    # ### end Alembic commands ###
