"""add consensus tracking

Revision ID: 7d4c14fae102
Revises: 9c14a8ea67ea
Create Date: 2026-05-25 20:14:46.430553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4c14fae102'
down_revision: Union[str, Sequence[str], None] = '9c14a8ea67ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_memories', sa.Column('agreement_count', sa.Integer(), nullable=False))
    op.add_column('room_memories', sa.Column('disagreement_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_memories', 'disagreement_count')
    op.drop_column('room_memories', 'agreement_count')
    # ### end Alembic commands ###
