"""Add RoomTask model properly

Revision ID: 8a17bdc117fc
Revises: bb0e4eb24ecc
Create Date: 2026-06-26 18:39:07.956723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a17bdc117fc'
down_revision: Union[str, Sequence[str], None] = 'bb0e4eb24ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
