"""add temporal cognition fields

Revision ID: b7259a11529b
Revises: e7bfd605ec5b
Create Date: 2026-05-25 20:03:56.075599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7259a11529b'
down_revision: Union[str, Sequence[str], None] = 'e7bfd605ec5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_memories', sa.Column('last_accessed_at', sa.DateTime(), nullable=False))
    op.add_column('room_memories', sa.Column('decay_factor', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_memories', 'decay_factor')
    op.drop_column('room_memories', 'last_accessed_at')
    # ### end Alembic commands ###
