"""Add RoomTask model

Revision ID: bb0e4eb24ecc
Revises: f6f91670a819
Create Date: 2026-06-26 18:38:34.360318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb0e4eb24ecc'
down_revision: Union[str, Sequence[str], None] = 'f6f91670a819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_tasks_assignee'), table_name='room_tasks')
    op.drop_index(op.f('ix_room_tasks_room_id'), table_name='room_tasks')
    op.drop_table('room_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assignee_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('room_tasks_room_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('room_tasks_pkey'))
    )
    op.create_index(op.f('ix_room_tasks_room_id'), 'room_tasks', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_tasks_assignee'), 'room_tasks', ['assignee_username'], unique=False)
    # ### end Alembic commands ###
