"""initial schema

Revision ID: e35ba8a81041
Revises: 
Create Date: 2026-06-16 13:10:08.325979

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import VECTOR
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35ba8a81041'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS vector"
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', VECTOR(384), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_room_created_at', 'messages', ['room_id', 'created_at'], unique=False)
    op.create_index('ix_messages_room_id', 'messages', ['room_id'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_table('room_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('times_referenced', sa.Integer(), nullable=False),
    sa.Column('agreement_count', sa.Integer(), nullable=False),
    sa.Column('disagreement_count', sa.Integer(), nullable=False),
    sa.Column('embedding', VECTOR(384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('last_reinforced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_memories_created_at', 'room_memories', ['created_at'], unique=False)
    op.create_index('ix_room_memories_created_by', 'room_memories', ['created_by'], unique=False)
    op.create_index('ix_room_memories_room_created_at', 'room_memories', ['room_id', 'created_at'], unique=False)
    op.create_index('ix_room_memories_room_id', 'room_memories', ['room_id'], unique=False)
    op.create_table('memory_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_memory_id', sa.Integer(), nullable=False),
    sa.Column('target_memory_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_memory_id'], ['room_memories.id'], ),
    sa.ForeignKeyConstraint(['target_memory_id'], ['room_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_edges')
    op.drop_index('ix_room_memories_room_id', table_name='room_memories')
    op.drop_index('ix_room_memories_room_created_at', table_name='room_memories')
    op.drop_index('ix_room_memories_created_by', table_name='room_memories')
    op.drop_index('ix_room_memories_created_at', table_name='room_memories')
    op.drop_table('room_memories')
    op.drop_table('room_memberships')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_room_id', table_name='messages')
    op.drop_index('ix_messages_room_created_at', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
