"""make message sender_id nullable

Revision ID: f6f91670a819
Revises: 3913073d7edf
Create Date: 2026-06-26 17:30:39.191022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f91670a819'
down_revision: Union[str, Sequence[str], None] = '3913073d7edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_room_membership_room_id', 'room_memberships', ['room_id'], unique=False)
    op.create_index('ix_room_membership_user_id', 'room_memberships', ['user_id'], unique=False)
    op.create_index('ix_room_membership_user_room', 'room_memberships', ['user_id', 'room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_membership_user_room', table_name='room_memberships')
    op.drop_index('ix_room_membership_user_id', table_name='room_memberships')
    op.drop_index('ix_room_membership_room_id', table_name='room_memberships')
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
